development:
  adapter: postgresql
  database: todonode
  user: steven
  password: null
  port: 5432
  host: localhost

test:
  adapter: postgresql
  database: todonode_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  port: 4242
  database: todo_production
  pool: 5
  timeout: 5000
  username: todo
  password: secret_todo_password
